'use client';

import * as React from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Skeleton } from '@/components/ui/skeleton';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Separator } from '@/components/ui/separator';
import type { CreditOffer } from '@/lib/types';
import { summarizeTerms } from '@/ai/flows/summarize-terms';
import { Loader, Sparkles, FileText, Play } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

interface OfferDetailsModalProps {
  offer: CreditOffer;
  isOpen: boolean;
  onOpenChange: (isOpen: boolean) => void;
}

export default function OfferDetailsModal({ offer, isOpen, onOpenChange }: OfferDetailsModalProps) {
  const [summary, setSummary] = React.useState<string | null>(null);
  const [isLoading, setIsLoading] = React.useState(false);
  const { toast } = useToast();

  const handleSummarize = async () => {
    setIsLoading(true);
    setSummary(null);
    try {
      const result = await summarizeTerms({ termsAndConditions: offer.termsAndConditions });
      setSummary(result.summary);
    } catch (error) {
      console.error('Failed to summarize terms:', error);
      toast({
        variant: "destructive",
        title: "Analysis Failed",
        description: "Could not generate summary. Please try again later.",
      })
    } finally {
      setIsLoading(false);
    }
  };

  React.useEffect(() => {
    if (isOpen) {
      // Prefetch the summary when the modal opens
      handleSummarize();
    } else {
      setSummary(null);
      setIsLoading(false);
    }
  }, [isOpen]);

  return (
    <Dialog open={isOpen} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-3xl bg-card/90 backdrop-blur-sm border-primary/20">
        <DialogHeader>
          <DialogTitle className="text-2xl font-headline text-primary drop-shadow-[0_0_4px_hsl(var(--primary))]">{offer.title}</DialogTitle>
          <DialogDescription>
            Offer from {offer.provider}
          </DialogDescription>
        </DialogHeader>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 max-h-[70vh]">
          <div className="flex flex-col gap-4">
            <h3 className="font-semibold font-headline text-lg">Terms & Conditions</h3>
            <ScrollArea className="h-96 rounded-md border p-4 text-sm whitespace-pre-wrap font-mono bg-background/50">
              {offer.termsAndConditions}
            </ScrollArea>
          </div>
          <div className="flex flex-col gap-4">
            <div className="flex justify-between items-center">
                <h3 className="font-semibold font-headline text-lg">AI-Powered Analysis</h3>
                <Button onClick={handleSummarize} disabled={isLoading} size="sm" className="bg-accent hover:bg-accent/90 shadow-lg shadow-accent/30">
                    {isLoading ? (
                        <Loader className="mr-2 h-4 w-4 animate-spin" />
                    ) : (
                        <Sparkles className="mr-2 h-4 w-4" />
                    )}
                    {isLoading ? 'Analyzing...' : 'Re-Analyze'}
                </Button>
            </div>
            <ScrollArea className="h-96 rounded-md border p-4 bg-background/50">
              {isLoading && (
                <div className="space-y-3">
                  <Skeleton className="h-4 w-full bg-muted/50" />
                  <Skeleton className="h-4 w-full bg-muted/50" />
                  <Skeleton className="h-4 w-5/6 bg-muted/50" />
                  <Skeleton className="h-4 w-full bg-muted/50" />
                  <Skeleton className="h-4 w-4/6 bg-muted/50" />
                </div>
              )}
              {summary && (
                 <Alert className="bg-transparent border-accent/50">
                    <Sparkles className="h-4 w-4 text-accent" />
                    <AlertTitle className="text-accent">Executive Summary</AlertTitle>
                    <AlertDescription>
                        <p className="text-foreground">{summary}</p>
                        <Separator className="my-2 bg-border/50" />
                        <p className="text-xs text-muted-foreground">This summary was generated by AI. Always refer to the original terms for complete details.</p>
                    </AlertDescription>
                </Alert>
              )}
              {!isLoading && !summary && (
                <div className="flex flex-col items-center justify-center h-full text-center">
                    <FileText className="h-12 w-12 text-muted-foreground/50 mb-4" />
                    <p className="text-muted-foreground">Could not generate summary. Please try again.</p>
                </div>
              )}
            </ScrollArea>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
